/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(atsc2_rx_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9ee26b665f286899cd3f61ee041fc28a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc2/atsc2_rx_filter.h>
// pydoc.h is automatically generated in the build directory
#include <atsc2_rx_filter_pydoc.h>

void bind_atsc2_rx_filter(py::module& m)
{

    using atsc2_rx_filter    = ::gr::atsc2::atsc2_rx_filter;


    py::class_<atsc2_rx_filter, gr::hier_block2,
        std::shared_ptr<atsc2_rx_filter>>(m, "atsc2_rx_filter", D(atsc2_rx_filter))

        .def(py::init(&atsc2_rx_filter::make),
           py::arg("rate"),
           py::arg("sps"),
           D(atsc2_rx_filter,make)
        )
        



        ;




}








