/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(atsc2_fpll.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ada25bb8c396678699954ad783beda29)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <atsc2/atsc2_fpll.h>
// pydoc.h is automatically generated in the build directory
#include <atsc2_fpll_pydoc.h>

void bind_atsc2_fpll(py::module& m)
{

    using atsc2_fpll    = ::gr::atsc2::atsc2_fpll;


    py::class_<atsc2_fpll, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<atsc2_fpll>>(m, "atsc2_fpll", D(atsc2_fpll))

        .def(py::init(&atsc2_fpll::make),
           py::arg("rate"),
           D(atsc2_fpll,make)
        )
        



        ;




}








